apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale-ingress-operator
  namespace: headscale-ingress-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headscale-ingress-operator-services
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headscale-ingress-operator-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headscale-ingress-operator-services
subjects:
  - kind: ServiceAccount
    name: headscale-ingress-operator
    namespace: headscale-ingress-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headscale-ingress-operator-records
  namespace: headscale
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["headscale-extra-records"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headscale-ingress-operator-records
  namespace: headscale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: headscale-ingress-operator-records
subjects:
  - kind: ServiceAccount
    name: headscale-ingress-operator
    namespace: headscale-ingress-operator
