apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headscale-ingress-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headscale-ingress-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "headscale-ingress-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "headscale-ingress-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headscale-ingress-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - --interval={{ .Values.config.interval }}
            - --headscale-namespace={{ .Values.headscale.namespace }}
            - --records-configmap={{ .Values.headscale.recordsConfigMap }}
            - --records-key={{ .Values.headscale.recordsKey }}
            - --allowed-zones={{ join "," .Values.config.allowedZones }}
            - --ingress-class={{ .Values.config.ingressClassName }}
            - --proxy-enabled={{ .Values.proxy.enabled }}
            - --proxy-headscale-server-url={{ .Values.headscale.serverURL }}
            - --proxy-headscale-pod-selector={{ .Values.headscale.podSelector }}
            - --proxy-headscale-container={{ .Values.headscale.container }}
            - --proxy-headscale-user={{ .Values.proxy.headscaleUser }}
            - --proxy-authkey-expiration={{ .Values.proxy.authKeyExpiration }}
            - --proxy-authkey-tags={{ join "," .Values.proxy.authKeyTags }}
            - --proxy-tailscale-image={{ .Values.proxy.tailscaleImage }}
            - --proxy-nginx-image={{ .Values.proxy.nginxImage }}
            - --proxy-default-tls-secret={{ .Values.proxy.defaultTLSSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
